# Generated by Django 4.2.7 on 2026-02-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_firebase_uuid_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="firebase_uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["firebase_uid"], name="users_firebas_361636_idx"
            ),
        ),
    ]
