# Generated by Django 4.2.7 on 2026-02-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_email_verified_first_name_guest_onetimetoken"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="onetimetoken",
            new_name="accounts_on_token_28a58d_idx",
            old_name="accounts_on_token_8a0f0d_idx",
        ),
    ]
