# Generated by Django 4.2.7 on 2026-01-28 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("barbershops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("is_booked", models.BooleanField(default=False)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "barber",
                    models.ForeignKey(
                        limit_choices_to={"role": "Barber"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "barbershop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="barbershops.barbershop",
                    ),
                ),
            ],
            options={
                "db_table": "time_slots",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_time", models.DateTimeField()),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            (
                                "Pending to be paid on cash",
                                "Pending to be paid on cash",
                            ),
                            ("Online Paid", "Online Paid"),
                            ("Online Pending", "Online Pending"),
                        ],
                        default="Pending to be paid on cash",
                        max_length=50,
                    ),
                ),
                (
                    "payment_intent_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                            ("Approved", "Approved"),
                        ],
                        default="Confirmed",
                        max_length=20,
                    ),
                ),
                ("customer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barber",
                    models.ForeignKey(
                        limit_choices_to={"role": "Barber"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barber_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "barbershop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="barbershops.barbershop",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"role": "Customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="services.service",
                    ),
                ),
                (
                    "slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking",
                        to="bookings.timeslot",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
            },
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["barber", "date"], name="time_slots_barber__26f491_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["barbershop", "date"], name="time_slots_barbers_595e60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["is_booked"], name="time_slots_is_book_8cf021_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["start_time", "end_time"], name="time_slots_start_t_7c83d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["barbershop"], name="bookings_barbers_fc2815_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["customer"], name="bookings_custome_59c648_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["barber"], name="bookings_barber__ded816_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["service"], name="bookings_service_876077_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_time"], name="bookings_booking_07a617_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["payment_status"], name="bookings_payment_3ea9ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["booking_status"], name="bookings_booking_ab1f8c_idx"
            ),
        ),
    ]
