# Generated by Django 4.2.7 on 2026-01-30 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_reminder_flags"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="timeslot",
            name="unique_booked_slot",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="customer_bookings_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="barbershop_status_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="timeslot",
            name="time_slots_barber_date_booked_idx",
        ),
    ]
