# Generated by Django 4.2.7 on 2026-01-30 12:37

import barbershops.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0005_review_model"),
        ("barbershops", "0005_barbershop_geo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 Stars"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ]
                    ),
                ),
                ("comment", models.TextField(max_length=1000)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "barbershop_reviews",
            },
        ),
        migrations.RemoveIndex(
            model_name="barbershop",
            name="shop_search_idx",
        ),
        migrations.RenameIndex(
            model_name="staffinvitation",
            new_name="barbershop__email_173ba6_idx",
            old_name="barbershop__email_9a1f2a_idx",
        ),
        migrations.AlterField(
            model_name="barbershop",
            name="opening_hours",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[barbershops.models.validate_opening_hours],
            ),
        ),
        migrations.AddIndex(
            model_name="barbershop",
            index=models.Index(fields=["slug"], name="barbershops_slug_18fbdd_idx"),
        ),
        migrations.AddIndex(
            model_name="barbershop",
            index=models.Index(
                fields=["subdomain"], name="barbershops_subdoma_d1db38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffinvitation",
            index=models.Index(fields=["token"], name="barbershop__token_0ebc42_idx"),
        ),
        migrations.AddField(
            model_name="review",
            name="barber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="barbershops.barbershopstaff",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="barbershop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="barbershops.barbershop",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="services.order",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["barbershop", "-created_at"],
                name="barbershop__barbers_5daed8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["barber", "-created_at"], name="barbershop__barber__a38ffd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="barbershop__rating_977525_idx"),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("booking__isnull", False)),
                fields=("booking",),
                name="unique_booking_review",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order__isnull", False)),
                fields=("order",),
                name="unique_order_review",
            ),
        ),
    ]
