# Generated by Django 4.2.7 on 2026-02-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_push_device_and_preferences"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pushdevice",
            new_name="push_device_user_id_8c34d3_idx",
            old_name="push_devic_user_id_idx",
        ),
        migrations.RenameIndex(
            model_name="pushdevice",
            new_name="push_device_expo_pu_e191e8_idx",
            old_name="push_devic_expo_token_idx",
        ),
    ]
