# Generated by Django 4.2.7 on 2026-02-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_idempotency_key"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="payment",
            new_name="payments_status_426d4f_idx",
            old_name="payments_status_created_idx",
        ),
    ]
